export enum FlightStatus {
  SCHEDULED = 'SCHEDULED',
  BOARDING = 'BOARDING',
  DEPARTED = 'DEPARTED',
  IN_FLIGHT = 'IN_FLIGHT',
  ARRIVED = 'ARRIVED',
  DELAYED = 'DELAYED',
  CANCELLED = 'CANCELLED',
}

export enum AircraftType {
  BOEING_737 = 'BOEING_737',
  BOEING_777 = 'BOEING_777',
  BOEING_787 = 'BOEING_787',
  AIRBUS_A320 = 'AIRBUS_A320',
  AIRBUS_A330 = 'AIRBUS_A330',
  AIRBUS_A350 = 'AIRBUS_A350',
}
